// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiQy_p5i5ojtr7O4ZhcMsXv3aO-Mke0f0',
    appId: '1:89306756252:web:b2084662c787929ee6e959',
    messagingSenderId: '89306756252',
    projectId: 'allogroup',
    authDomain: 'allogroup.firebaseapp.com',
    storageBucket: 'allogroup.appspot.com',
    measurementId: 'G-M5K2T7JTDY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2TMY3WFxZT5liTPtyy2pVpdPcWuDG2Vg',
    appId: '1:89306756252:android:e85ea1eafa0b0e2ce6e959',
    messagingSenderId: '89306756252',
    projectId: 'allogroup',
    storageBucket: 'allogroup.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6wKhgibvtSAx_0N-AYA0WCpVAukV1WXg',
    appId: '1:89306756252:ios:96d12f0ac23c0cfce6e959',
    messagingSenderId: '89306756252',
    projectId: 'allogroup',
    storageBucket: 'allogroup.appspot.com',
    iosBundleId: 'com.example.allogroup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6wKhgibvtSAx_0N-AYA0WCpVAukV1WXg',
    appId: '1:89306756252:ios:8c753b31e13f1d97e6e959',
    messagingSenderId: '89306756252',
    projectId: 'allogroup',
    storageBucket: 'allogroup.appspot.com',
    iosBundleId: 'com.example.allogroup.RunnerTests',
  );
}
