// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5RGQzj1CdR_A5TOjRXUcw1Q7K_iOEfd8',
    appId: '1:247964597670:web:2b0495a8a3431a3b7ce367',
    messagingSenderId: '247964597670',
    projectId: 'allodatabase',
    authDomain: 'allodatabase.firebaseapp.com',
    storageBucket: 'allodatabase.appspot.com',
    measurementId: 'G-X56CDP0J6V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBddRjYD_gVfk_uatGovxOHU1bR3R0H44Y',
    appId: '1:247964597670:android:f2060faa1dc611947ce367',
    messagingSenderId: '247964597670',
    projectId: 'allodatabase',
    storageBucket: 'allodatabase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADnPjL66tPP7d7aMYDyQsc8_L5x-92pFc',
    appId: '1:247964597670:ios:bcac6c5c86a0ba8b7ce367',
    messagingSenderId: '247964597670',
    projectId: 'allodatabase',
    storageBucket: 'allodatabase.appspot.com',
    iosBundleId: 'com.example.allogroup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADnPjL66tPP7d7aMYDyQsc8_L5x-92pFc',
    appId: '1:247964597670:ios:a3332f3c24c55cfe7ce367',
    messagingSenderId: '247964597670',
    projectId: 'allodatabase',
    storageBucket: 'allodatabase.appspot.com',
    iosBundleId: 'com.example.allogroup.RunnerTests',
  );
}
