// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAt4VPS-YSo-lyKqUzXJEcHTthwHbBtNLQ',
    appId: '1:570659806740:web:b69f3c7b69d6e2a4c61101',
    messagingSenderId: '570659806740',
    projectId: 'allogroup-bfda9',
    authDomain: 'allogroup-bfda9.firebaseapp.com',
    storageBucket: 'allogroup-bfda9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdW0PXdfhIHQNTNjajgp9QVESWkzIRWjk',
    appId: '1:570659806740:android:55cc462560e654bbc61101',
    messagingSenderId: '570659806740',
    projectId: 'allogroup-bfda9',
    storageBucket: 'allogroup-bfda9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBY2usrZbtPXNdo7G7gHZaYLu2trWeFuZ0',
    appId: '1:570659806740:ios:9dc96ccc7f0b977ac61101',
    messagingSenderId: '570659806740',
    projectId: 'allogroup-bfda9',
    storageBucket: 'allogroup-bfda9.appspot.com',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBY2usrZbtPXNdo7G7gHZaYLu2trWeFuZ0',
    appId: '1:570659806740:ios:9c6534e3276a3f28c61101',
    messagingSenderId: '570659806740',
    projectId: 'allogroup-bfda9',
    storageBucket: 'allogroup-bfda9.appspot.com',
    iosBundleId: 'com.example.mobile.RunnerTests',
  );
}
